---
title: "Доклад"
subtitle: "Архитектура, параметры и организация беспроводных сетей"

author:
  name: "Богомолова Полина Петровна"
  degrees: "студент"
  email: "1032253562@rudn.ru"
  affiliation:
    - name: "Российский университет дружбы народов"
      country: "Российская Федерация"
      postal-code: "117198"
      city: "Москва"
      address: "ул. Миклухо-Маклая, д. 6"

format:
  pdf:
    pdf-engine: xelatex
---


# Введение

	Беспроводная сеть - это компьютерная сеть, в которой используются беспроводные соединения для передачи данных между узлами сети. Для передачи данных используются радиоволны.
	
	Беспроводные сети широко применяются. К примеру, сотовые телефоны, которые являются частью повседневных беспроводных сетей, позволяют легко поддерживать связь между людьми даже на дальних расстояниях. Другой пример — межконтинентальные сетевые системы, использующие спутники для связи по всему миру. Экстренные службы, такие как полиция, также используют беспроводные сети для эффективной коммуникации. Отдельные лица и компании используют беспроводные сети для быстрой отправки и обмена данными, будь то в небольшом офисном здании или по всему миру.
	
	
# Архитектура беспроводных сетей

	IEEE 802.11 — набор стандартов беспроводной связи с использованием радиоволн (частотные диапазоны 0,9; 2,4; 3,6; 5; 6 и 60 ГГц) и видимого света (Li-Fi), предназначенный для создания компьютерных сетей. Пользователям он более известен по названию Wi-Fi, фактически являющемуся брендом, предложенным и продвигаемым организацией Wi-Fi Alliance. В инфраструктурном режиме используется точка доступа (к примеру, роутер), с помощью которой осуществляется взаимодействие устройств сети.

	Точка доступа - это устройство, которое осуществляет подключение беспроводных клиентов к проводной сети. Функции:централизованное управление и передача данных между устройствами.
	
	Беспроводная ad-hoc-сеть (беспроводная динамическая сеть, беспроводная самоорганизующаяся сеть) — децентрализованная беспроводная сеть, в которой устройства взаимодействуют напрямую.
	
	Mesh-сеть - это сеть, которая позволяет узлам передавать данные друг через друга, обеспечивает устойчивость и расширение покрытия.


# Основные параметры беспроводных сетей
	
	Частота и длина волны являются важными характеристиками беспроводных сетей, которые влияют на скорость передачи данных и расстояние, на котором сигнал остается сильным и стабильным.
	
	Частота 2,4 ГГц обеспечивает большее расстояние, но могут быть помехи. Частота 5,5 ГГц обеспечивает более высокую скорость передачи данных. Скорость передачи данных зависит от ширины канала, используемых технологий, стандарта.
	
	Технология MU MIMO (multiple input, multiple output) позволяет передавать данные на несколько подключенных устройств одновременно, что уменьшает время ожидания для каждого из них.
	
	Соотношение сигнал/шум - это показатель чистоты звука, который помогает определить качество канала связи. Чем выше соотношение, тем чище и качественнее звук (snr измеряется в децибелах).
	
	Задержка передачи данных (латентность) - реальное время отклика по сравнению с ожидаемым. Приложения для общения в реальном времени, стриминга и проведения транзакций сильно зависят от времени ожидания. Увеличение задержки всего на несколько секунд может привести к искажению изображений и голосов, к финансовым потерям, к зависаниям.
	
	
# Организация беспроводных сетей

	Организация беспроводной сети начинается с планирования зоны покрытия. На этом этапе планируется место размещения точек доступа, чтобы обеспечить стабильный сигнал на всей зоне покрытия. Цель: избежать зоны с нестабильным или отсутствующим сигналом и обеспечить равномерное покрытие. При проектировании учитываются площадь помещения, количество пользователей и назначение сети.
	
	На распространение сигнала влияют физические препятствия (стены, мебель). Чем больше препятствий, тем ниже скорость передачи данных и тем слабее будет сигнал. В больших помещениях часто устанавливают несколько точек доступа для равномерного покрытия и стабильного сигнала.
	
	В беспроводных сетях используется несколько каналов передачи данных. В диапазоне 2,4 ГГц их количество ограничено и они могут пересекаться, вызывая помехи. Для уменьшения интерференции выбираются неперекрывающиеся каналы или ипользуется диапазон с частотой 5 ГГц.
	В Wi-Fi исопользуется метод CSMA/CA , который предотвращает одновременную передачу данных несколькими устройствами. Перед отправкой данных устройство проверяет, свободен ли канал. Если канал занят, оно ждет, если свободен - начинает передачу данных.
	
	Для защиты беспроводных сетей используются протоколы WPA2 И WPA3. Они обеспечивают шифрование данных и защиту от несанкционированного доступа. WPA3 является более современным, он улучшает защиту от подбора пароля и от атак на публичные сети.
	
	
# Заключение

	Беспроводные сети являются основной технологией современной информационной инфраструктуры. Они обеспечивают передачу данных без использования проводных соединений и позволяет пользователям подключаться к сети даже в не столь близком месте. В ходе развития беспроводных технологий сформировлаись различные архитектурные подходы, такие как инфраструктурный, ad-hoc, mesh-режимы, каждый из которых применяется в зависимости от условий и задач сети. Наиболее распространенным является инфраструктурный режим, так как он обеспечивает  централизованное управление и более стабильный сигнал. Развитие беспроводрных сетей активно продолжается в направлении увеличения скорости передачи данных, снижения задержек и повышения уровня безопасности, что делает их основой современной цифровой среды
	

# Список литературы{.unnumbered}

1. Беспроводная сеть // Википедия. - URL: https://en.wikipedia.org/wiki/Wireless_network
2. IEE 802.11 // Википедия. - URL: https://ru.wikipedia.org/wiki/IEEE_802.11
3. Беспроводная точка доступа // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D1%82%D0%BE%D1%87%D0%BA%D0%B0_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0
4. Беспроводная ad-hoc сеть // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_ad-hoc-%D1%81%D0%B5%D1%82%D1%8C
5. Ячеистая топология // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%AF%D1%87%D0%B5%D0%B8%D1%81%D1%82%D0%B0%D1%8F_%D1%82%D0%BE%D0%BF%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F?ysclid=mo04k1i0pu33362885
6. Диапазон частот Wi-Fi // t2. - URL: https://msk.t2.ru/journal/article/wi-fi-frequency-range
7. Технология MU MIMO // dns. - URL: https://club.dns-shop.ru/wiki/t-280-marshrutizatoryi/123538-tehnologiya-mu-mimo-v-routere-chto-eto-i-dlya-chego-nujna/
8. Что такое SNR в аудио? // 8ohm. - URL: https://8ohm.ru/news/chto-takoe-snr-v-audio-1486

