project:
  title: "report"
  output-dir: "_output"

lang: ru-RU

format:
  pdf:
    pdf-engine: xelatex

    mainfont: "DejaVu Sans"
    sansfont: "DejaVu Sans"
    monofont: "DejaVu Sans"
   

    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5

    toc: true
    number-sections: true
    toc-depth: 2

    babel-lang: russian

  docx:
    toc: true
    number-sections: true
    toc-depth: 2

number-sections: true
toc: true
toc-title: "Содержание"

bibliography:
  - bib/cite.bib

csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl
