---
title: "Доклад"
subtitle: "Архитектура, параметры и организация беспроводных сетей"
author: "Богомолова Полина Петровна"
date: today
lang: ru
format:
  html:
    theme: cosmo
  beamer:
    theme: Madrid
---

# Информация о докладчике

- Богомолова Полина Петровна
- ФФМиЕН
- НКАбд01-25 
- 1032253562  

---

# Введение

	Беспроводная сеть - это компьютерная сеть, в которой используются беспроводные соединения для передачи данных между узлами сети. Для передачи данных используются радиоволны. 
	Беспроводные сети имеют широкое применение:
- сотовые телефоны
- межконтинентальные сетевые системы
- экстренные службы
 
---

# Архитектура беспроводных сетей

	IEEE 802.11 — набор стандартов беспроводной связи с использованием радиоволн (частотные диапазоны 0,9; 2,4; 3,6; 5; 6 и 60 ГГц) и видимого света (Li-Fi), предназначенный для создания компьютерных сетей. 
	Точка доступа - устройство, которое осуществляет подключение беспроводных клиентов к проводной сети. Функции:централизованное управление и передача данных между устройствами.
	Беспроводная ad-hoc-сеть — устройства взаимодействуют напрямую.
	Mesh-сеть -позволяет узлам передавать данные друг через друга

---

# Основные параметры

- частота
- соотношение сигнал/шум
- задержка передачи данных (латентность)

---

# Технология передачи данных

	Технология MU MIMO (multiple input, multiple output) позволяет передавать данные на несколько подключенных устройств одновременно, что уменьшает время ожидания для каждого из них.

---

# Качество соединения

	Частота 2,4 ГГц обеспечивает большее расстояние, но могут быть помехи. Частота 5,5 ГГц обеспечивает более высокую скорость передачи данных. Скорость передачи данных зависит от ширины канала, используемых технологий, стандарта.

	Частота и длина волны являются важными характеристиками беспроводных сетей, которые влияют на скорость передачи данных и расстояние, на котором сигнал остается сильным и стабильным.
	
	Задержка передачи данных (латентность) - реальное время отклика по сравнению с ожидаемым. Приложения для общения в реальном времени, стриминга и проведения транзакций сильно зависят от времени ожидания. Увеличение задержки всего на несколько секунд может привести к искажению изображений и голосов, к финансовым потерям, к зависаниям.

---

# Организация сети


---

# Безопасность


---

# Заключение

	Беcпроводные сети являются основной технологией современной информационной инфраструктуры. Они обеспечивают передачу данных без использования проводных соединений и позволяет пользователям подключаться к сети даже в не столь близком месте. Развитие беспроводрных сетей активно продолжается в направлении увеличения скорости передачи данных, снижения задержек и повышения уровня безопасности, что делает их основой современной цифровой среды

---

# Список литературы

1. Беспроводная сеть // Википедия. - URL: https://en.wikipedia.org/wiki/Wireless_network
2. IEE 802.11 // Википедия. - URL: https://ru.wikipedia.org/wiki/IEEE_802.11
3. Беспроводная точка доступа // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D1%82%D0%BE%D1%87%D0%BA%D0%B0_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0
4. Беспроводная ad-hoc сеть // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%81%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_ad-hoc-%D1%81%D0%B5%D1%82%D1%8C
5. Ячеистая топология // Википедия. - URL: https://ru.wikipedia.org/wiki/%D0%AF%D1%87%D0%B5%D0%B8%D1%81%D1%82%D0%B0%D1%8F_%D1%82%D0%BE%D0%BF%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F?ysclid=mo04k1i0pu33362885
6. Диапазон частот Wi-Fi // t2. - URL: https://msk.t2.ru/journal/article/wi-fi-frequency-range
7. Технология MU MIMO // dns. - URL: https://club.dns-shop.ru/wiki/t-280-marshrutizatoryi/123538-tehnologiya-mu-mimo-v-routere-chto-eto-i-dlya-chego-nujna/
8. Что такое SNR в аудио? // 8ohm. - URL: https://8ohm.ru/news/chto-takoe-snr-v-audio-1486

---

# Спасибо за внимание
